package com.bank.atm.gui.transactions;

import javax.swing.*;
import java.awt.*;
import java.text.NumberFormat;
import java.util.Locale;

public class DepositUI extends JFrame {

    private final int frameWidth = 500;
    private final int frameHeight = 500;


    private JPanel depositPanel;
    private JLabel amountLabel;
    private JFormattedTextField depositAmountField;
    private JComboBox chooseAccountComboBox;
    private JLabel currencyTypeLabel;

    /**
     * TODO add field for choosing account to make deposit and adjust currency format according to locale of that account
     */
    public DepositUI() {

        $$$setupUI$$$();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setContentPane(depositPanel);//sets content to our menu panel
        this.setPreferredSize(new Dimension(frameWidth, frameHeight));//set width and height of our frame
        this.pack(); //packs frame to preferred size
    }

    private void createUIComponents() {
        depositAmountField = new JFormattedTextField(NumberFormat.getCurrencyInstance(Locale.US));
        amountLabel.setLabelFor(depositAmountField);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        depositPanel = new JPanel();
        depositPanel.setLayout(new GridBagLayout());
        amountLabel = new JLabel();
        amountLabel.setText("Amount");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        depositPanel.add(amountLabel, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        depositPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        depositPanel.add(spacer2, gbc);
        depositAmountField = new JFormattedTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        depositPanel.add(depositAmountField, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Choose Account");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        depositPanel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Make Deposit");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        depositPanel.add(label2, gbc);
        chooseAccountComboBox = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        depositPanel.add(chooseAccountComboBox, gbc);
        currencyTypeLabel = new JLabel();
        currencyTypeLabel.setText("USD");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        depositPanel.add(currencyTypeLabel, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        depositPanel.add(spacer3, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return depositPanel;
    }

}
