package com.bank.atm.gui.transactions;

import javax.swing.*;
import java.awt.*;

public class TransferMoneyUI extends JFrame {

    private final int frameWidth = 500;
    private final int frameHeight = 500;

    private JPanel transferMoneyPanel;
    private JComboBox fromAccountComboBox;
    private JComboBox toAccountComboBox;
    private JLabel fromAccountCurrencyType;
    private JLabel toAccountCurrencyType;
    private JFormattedTextField transactionFeeTextField;
    private JFormattedTextField transferAmount;
    private JFormattedTextField convertedTransferAmount;
    private JFormattedTextField fromAccountBalanceTextField;
    private JFormattedTextField toAccountBalanceTextField;


    public TransferMoneyUI() {

        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setContentPane(transferMoneyPanel);//sets content to our menu panel
        this.setPreferredSize(new Dimension(frameWidth, frameHeight));//set width and height of our frame
        this.pack(); //packs frame to preferred size
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        transferMoneyPanel = new JPanel();
        transferMoneyPanel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Transfer Money");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        transferMoneyPanel.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        transferMoneyPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        transferMoneyPanel.add(spacer2, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("From:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        transferMoneyPanel.add(label2, gbc);
        fromAccountComboBox = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        transferMoneyPanel.add(fromAccountComboBox, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        transferMoneyPanel.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.VERTICAL;
        transferMoneyPanel.add(spacer4, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("To:");
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        transferMoneyPanel.add(label3, gbc);
        toAccountComboBox = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        transferMoneyPanel.add(toAccountComboBox, gbc);
        transferAmount = new JFormattedTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        transferMoneyPanel.add(transferAmount, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Amount:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        transferMoneyPanel.add(label4, gbc);
        fromAccountCurrencyType = new JLabel();
        fromAccountCurrencyType.setText("USD");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        transferMoneyPanel.add(fromAccountCurrencyType, gbc);
        toAccountCurrencyType = new JLabel();
        toAccountCurrencyType.setText("JPY");
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        transferMoneyPanel.add(toAccountCurrencyType, gbc);
        transactionFeeTextField = new JFormattedTextField();
        transactionFeeTextField.setEditable(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        transferMoneyPanel.add(transactionFeeTextField, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("transaction fee:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        transferMoneyPanel.add(label5, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("USD");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        transferMoneyPanel.add(label6, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Balance:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        transferMoneyPanel.add(label7, gbc);
        convertedTransferAmount = new JFormattedTextField();
        convertedTransferAmount.setEditable(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        transferMoneyPanel.add(convertedTransferAmount, gbc);
        fromAccountBalanceTextField = new JFormattedTextField();
        fromAccountBalanceTextField.setEditable(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        transferMoneyPanel.add(fromAccountBalanceTextField, gbc);
        toAccountBalanceTextField = new JFormattedTextField();
        toAccountBalanceTextField.setEditable(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        transferMoneyPanel.add(toAccountBalanceTextField, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        transferMoneyPanel.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        transferMoneyPanel.add(spacer6, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return transferMoneyPanel;
    }

}
