package com.bank.atm.gui.transactions;
/**
 * UI for viewing transactions
 * @author Sandra Zhen
 */

import com.bank.atm.backend.accounts.Account;
import com.bank.atm.backend.collections.TransactionsCollectionManager;
import com.bank.atm.backend.users.User;
import com.bank.atm.backend.transactions.Transaction;
import com.bank.atm.gui.util_gui.AccountListRenderer;
import com.bank.atm.util.Formatter;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.*;
import java.util.List;

public class ViewTransactionsUI extends JFrame {
    private final int frameWidth = 100;
    private final int frameHeight = 100;
    private JList transactionsList;
    private JPanel viewTransactionsPanel;
    private JLabel viewTransactionsLabel;

    /**
     * Constructs UI to view transactions associated with account
     *
     * @param account
     */
    public ViewTransactionsUI(Account account) {
        super("Transactions for " + Formatter.splitCamelCase(account.getClass().getSimpleName()) + ": " + account.getID());
        $$$setupUI$$$();
        initGUI();
        viewTransactionsLabel.setText("Transactions for " + Formatter.splitCamelCase(account.getClass().getSimpleName()) + ": " + account.getID());
        initTransactionsList(TransactionsCollectionManager.getInstance().allTransactionsForAccount(account.getID()));
    }

    /**
     * Constructs UI to view transactions associated with user
     *
     * @param user
     */
    public ViewTransactionsUI(User user) {
        super(user.getFirstName() + " " + user.getLastName() + "\'s Transactions");
        $$$setupUI$$$();
        initGUI();
        viewTransactionsLabel.setText(user.getFirstName() + " " + user.getLastName() + "\'s Transactions");
        initTransactionsList(TransactionsCollectionManager.getInstance().allTransactionsForUser(user.getID()));
    }

    //initializes frame window and other gui components such as buttons
    private void initGUI() {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setContentPane(viewTransactionsPanel);//sets content to our menu panel
        this.setPreferredSize(new Dimension(frameWidth, frameHeight));//set width and height of our frame
        this.pack();

    }

    private void initTransactionsList(List<Transaction> transactionList) {
        transactionsList.setListData(transactionList.toArray());
        transactionsList.setCellRenderer(new AccountListRenderer(2, 15));
        transactionsList.setBorder(new EmptyBorder(10, 10, 10, 10));
        transactionsList.addListSelectionListener(new ListSelectionListener() {
            int i = 0;

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (i % 2 == 0) {//every click of list selection listener results in valueChanged being called twice. We use counter%2 to make sure the event is triggered only once
                    //code runs when item from transactions list is clicked
                }
                i++;
            }
        });
    }

    private void createUIComponents() {

        transactionsList = new JList<Transaction>();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        viewTransactionsPanel = new JPanel();
        viewTransactionsPanel.setLayout(new GridBagLayout());
        final JScrollPane scrollPane1 = new JScrollPane();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        viewTransactionsPanel.add(scrollPane1, gbc);
        scrollPane1.setViewportView(transactionsList);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        viewTransactionsPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        viewTransactionsPanel.add(spacer2, gbc);
        viewTransactionsLabel = new JLabel();
        viewTransactionsLabel.setText("View Transactions");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        viewTransactionsPanel.add(viewTransactionsLabel, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return viewTransactionsPanel;
    }
}
