package com.bank.atm.gui.user;

import javax.swing.*;
import java.awt.*;

/**
 * The UI for showing the full account details
 *
 * @author Sandra Zhen
 */
public class AccountDetails extends JFrame {
    private final int frameWidth = 500;
    private final int frameHeight = 500;

    private JButton depositButton;
    private JButton withdrawButton;
    private JPanel transactionPanel;
    private JLabel balanceValueLabel;
    private JComboBox currencyTypeComboBox;
    private JPanel accountDetailsPanel;
    private JLabel accountTypeValueLabel;
    private JPanel accountDetailsMainPanel;

    public AccountDetails(/*Account account*/) {
        $$$setupUI$$$();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setContentPane(accountDetailsMainPanel);//sets content to our menu panel
        this.setPreferredSize(new Dimension(frameWidth, frameHeight));//set width and height of our frame
        this.pack();

    }


    private void createUIComponents() {
        // TODO: place custom component creation code here. dynamically generate components based on what account is created in the accountDetails panel
        currencyTypeComboBox = new JComboBox();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        accountDetailsMainPanel = new JPanel();
        accountDetailsMainPanel.setLayout(new GridBagLayout());
        accountDetailsPanel = new JPanel();
        accountDetailsPanel.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        accountDetailsMainPanel.add(accountDetailsPanel, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Current Balance");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 10, 10, 10);
        accountDetailsPanel.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        accountDetailsPanel.add(spacer1, gbc);
        balanceValueLabel = new JLabel();
        balanceValueLabel.setText("0.00");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(20, 20, 20, 20);
        accountDetailsPanel.add(balanceValueLabel, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Currency Type:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 10, 10, 10);
        accountDetailsPanel.add(label2, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        accountDetailsPanel.add(currencyTypeComboBox, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Account Type:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 10, 0, 10);
        accountDetailsPanel.add(label3, gbc);
        accountTypeValueLabel = new JLabel();
        accountTypeValueLabel.setText("Checkings");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        accountDetailsPanel.add(accountTypeValueLabel, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        accountDetailsPanel.add(spacer2, gbc);
        final JLabel label4 = new JLabel();
        label4.setHorizontalAlignment(2);
        label4.setHorizontalTextPosition(0);
        label4.setText("Account Name Details");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.NORTH;
        accountDetailsMainPanel.add(label4, gbc);
        transactionPanel = new JPanel();
        transactionPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.BOTH;
        accountDetailsMainPanel.add(transactionPanel, gbc);
        depositButton = new JButton();
        depositButton.setText("Deposit");
        transactionPanel.add(depositButton);
        withdrawButton = new JButton();
        withdrawButton.setText("Withdraw");
        transactionPanel.add(withdrawButton);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        gbc.insets = new Insets(30, 0, 0, 0);
        accountDetailsMainPanel.add(spacer3, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return accountDetailsMainPanel;
    }
}
