package com.bank.atm.gui.user;
/**
 * Interface for user to view all accounts they have in the bank
 * @author Sandra Zhen
 *
 */

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

public class UserViewAccounts extends JFrame {

    private final int frameWidth = 500;
    private final int frameHeight = 500;

    private JPanel userViewAccountsPanel;
    private JButton addNewAcountButton;
    private JPanel accountsPanel;

    public UserViewAccounts(String userID) {

        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setContentPane(userViewAccountsPanel);//sets content to our menu panel
        this.setPreferredSize(new Dimension(frameWidth, frameHeight));//set width and height of our frame
        this.pack();
        addNewAcountButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                UserAddAccount userAddAccount = new UserAddAccount(userID);
                userAddAccount.setVisible(true);
            }
        });
        initAccountsPanel(userID);
    }

    private void initAccountsPanel(String userID) {
        BoxLayout boxLayout = new BoxLayout(accountsPanel, BoxLayout.Y_AXIS);
        accountsPanel.setLayout(boxLayout);
        List<JButton> acctBtns = createAccountBtns(userID);
        for (JButton acctBtn : acctBtns) {
            accountsPanel.add(Box.createRigidArea(new Dimension(10, 10)));//add space padding between each btn
            acctBtn.setMargin(new Insets(10, 100, 10, 100));
            accountsPanel.add(acctBtn);
        }

    }

    /**
     * populates the gui view with user account btns
     *
     * @param userID
     * @return
     */
    private List<JButton> createAccountBtns(String userID) {
        List<JButton> acctBtns = new ArrayList<>();
        for (String account : getAccounts(userID)) {//todo replace string with account obj
            JButton acctBtn = new JButton(account);
            acctBtn.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    System.out.println("Replace this with go to account details: " + account);
                    AccountDetails accountDetails = new AccountDetails();
                    accountDetails.setVisible(true);
                }
            });
            acctBtns.add(acctBtn);
        }

        return acctBtns;
    }

    /**
     * Retrieves all accounts that the current user has
     *
     * @param userID - id of user to get accounts for
     * @return list of accounts of the user
     */
    //TODO replace String with Account model if one is created later
    private List<String> getAccounts(String userID) {
        List<String> accList = new ArrayList<>();
        for (int i = 0; i < 10; i++) {//todo replace this with user's actual accounts
            accList.add("SampleAcc " + i + " and details here");

        }
        return accList;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        userViewAccountsPanel = new JPanel();
        userViewAccountsPanel.setLayout(new GridBagLayout());
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        userViewAccountsPanel.add(panel1, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label1, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        userViewAccountsPanel.add(panel2, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Accounts");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label2, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 200, 0, 0);
        panel2.add(spacer1, gbc);
        addNewAcountButton = new JButton();
        addNewAcountButton.setText("Add New Acount");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(addNewAcountButton, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setVerticalScrollBarPolicy(20);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        userViewAccountsPanel.add(scrollPane1, gbc);
        accountsPanel = new JPanel();
        accountsPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        scrollPane1.setViewportView(accountsPanel);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return userViewAccountsPanel;
    }
}
