package com.bank.atm.gui.user;
/**
 * Interface for users to add new account
 *
 * @author Sandra Zhen
 */
import com.bank.atm.backend.accounts.Account;
import com.bank.atm.backend.accounts.AccountFactory;
import com.bank.atm.backend.accounts.AccountType;
import com.bank.atm.backend.currency.Currency;
import com.bank.atm.backend.currency.Euro;
import com.bank.atm.backend.currency.JPY;
import com.bank.atm.backend.currency.USD;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;


public class UserAddAccount extends JFrame {
    private final int frameWidth = 500;
    private final int frameHeight = 500;

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        userAddAccountPanel = new JPanel();
        userAddAccountPanel.setLayout(new GridBagLayout());
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        userAddAccountPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        gbc.insets = new Insets(20, 0, 0, 0);
        userAddAccountPanel.add(spacer2, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Type of Account:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        userAddAccountPanel.add(label1, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        userAddAccountPanel.add(accountTypeComboBox, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Currency Type:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        userAddAccountPanel.add(label2, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        userAddAccountPanel.add(currencyTypeComboBox, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Account Name:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        userAddAccountPanel.add(label3, gbc);
        accountNameTextArea = new JTextArea();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.BOTH;
        userAddAccountPanel.add(accountNameTextArea, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        gbc.insets = new Insets(20, 0, 0, 0);
        userAddAccountPanel.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        gbc.insets = new Insets(20, 0, 0, 0);
        userAddAccountPanel.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.VERTICAL;
        userAddAccountPanel.add(spacer5, gbc);
        createAccountButton = new JButton();
        createAccountButton.setText("Create Account");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        userAddAccountPanel.add(createAccountButton, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Create New Account");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.NORTHWEST;
        userAddAccountPanel.add(label4, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return userAddAccountPanel;
    }

    private enum CurrencyType {
        USD, JPY, EURO
    }

    private JPanel userAddAccountPanel;
    private JComboBox<AccountType> accountTypeComboBox;
    private JComboBox<CurrencyType> currencyTypeComboBox;
    private JTextArea accountNameTextArea;
    private JButton createAccountButton;

    /**
     * @param userID - ID of user to add account for
     */
    public UserAddAccount(String userID) {

        $$$setupUI$$$();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setContentPane(userAddAccountPanel);//sets content to our menu panel
        this.setPreferredSize(new Dimension(frameWidth, frameHeight));//set width and height of our frame
        this.pack();

        createAccountButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //todo when createAccount button is clicked, create account.
                createAccount();
                System.out.println("Account is being created");
            }
        });

    }


    private void createUIComponents() {
        accountTypeComboBox = new JComboBox<AccountType>(AccountType.values());

        currencyTypeComboBox = new JComboBox<>(CurrencyType.values());


    }

    /**
     * Calls the account factory to create the appropriate account
     *
     * @return
     */
    private Account createAccount() {

        switch (accountTypeComboBox.getPrototypeDisplayValue()) {
            case BASIC_CHECKING_ACCOUNT:
                break;
            case FOUR_OH_ONE_K_ACCOUNT:
                break;
            case GENERIC_LOAN_ACCOUNT:
                break;
            case HIGH_INTEREST_SAVINGS_ACCOUNT:
                break;
            case LOW_INTEREST_SAVINGS_ACCOUNT:
                break;
            case PREMIUM_CHECKING_ACCOUNT:
                break;
        }
        Currency currency;
        switch (currencyTypeComboBox.getPrototypeDisplayValue()) {
            case USD:
                currency = USD.getInstance();
                break;
            case JPY:
                currency = JPY.getInstance();
                break;
            case EURO:
                currency = Euro.getInstance();
                break;
        }
        return null;//AccountFactory.createAccount(,currency,0,user);
    }

}
