package com.bank.atm.gui.login;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class ForgotPassword extends JFrame {
    private JPanel forgotPasswordPanel;
    private JLabel recoveryPhoneNumberLabel;
    private JTextField phoneNumberTextField;
    private JButton sendOTPButton;
    private JTextField userNameTextField;
    private JLabel userNameLabel;

    public ForgotPassword(String title) {
        super(title);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setContentPane(forgotPasswordPanel);
        this.setPreferredSize(new Dimension(500, 500));//set width and height of our frame
        this.pack();
        sendOTPButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // To-do : Do a reset password operation.
                dispose();
                JFrame frame = new Login("Login");
                frame.setVisible(true);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        forgotPasswordPanel = new JPanel();
        forgotPasswordPanel.setLayout(new GridBagLayout());
        recoveryPhoneNumberLabel = new JLabel();
        recoveryPhoneNumberLabel.setText("Recovery Phone Number");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        forgotPasswordPanel.add(recoveryPhoneNumberLabel, gbc);
        phoneNumberTextField = new JTextField();
        phoneNumberTextField.setMinimumSize(new Dimension(100, 30));
        phoneNumberTextField.setPreferredSize(new Dimension(100, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        forgotPasswordPanel.add(phoneNumberTextField, gbc);
        sendOTPButton = new JButton();
        sendOTPButton.setText("Send OTP");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        forgotPasswordPanel.add(sendOTPButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        forgotPasswordPanel.add(spacer1, gbc);
        userNameLabel = new JLabel();
        userNameLabel.setText("User Name");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        forgotPasswordPanel.add(userNameLabel, gbc);
        userNameTextField = new JTextField();
        userNameTextField.setMinimumSize(new Dimension(100, 30));
        userNameTextField.setPreferredSize(new Dimension(100, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        forgotPasswordPanel.add(userNameTextField, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return forgotPasswordPanel;
    }
}
