package com.bank.atm.gui.login;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class SignUp extends JFrame {

    private JPanel signUpPanel;
    private JTextField nameTextField;
    private JTextField phoneNumberTextField;
    private JTextField userNameTextField;
    private JLabel nameLabel;
    private JLabel phoneNumberLabel;
    private JLabel userNameLabel;
    private JLabel passwordLabel;
    private JPasswordField passwordPasswordField;
    private JButton signUpButton;

    public SignUp(String title) {
        super(title);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setContentPane(signUpPanel);
        this.setPreferredSize(new Dimension(500, 500));//set width and height of our frame
        this.pack();


        signUpButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // To-Do : Add user to file
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        signUpPanel = new JPanel();
        signUpPanel.setLayout(new GridBagLayout());
        signUpPanel.setName("Sign Up");
        nameLabel = new JLabel();
        nameLabel.setText("Name");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        signUpPanel.add(nameLabel, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        signUpPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        signUpPanel.add(spacer2, gbc);
        nameTextField = new JTextField();
        nameTextField.setMinimumSize(new Dimension(100, 30));
        nameTextField.setPreferredSize(new Dimension(100, 30));
        nameTextField.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        signUpPanel.add(nameTextField, gbc);
        phoneNumberLabel = new JLabel();
        phoneNumberLabel.setText("Phone Number");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        signUpPanel.add(phoneNumberLabel, gbc);
        phoneNumberTextField = new JTextField();
        phoneNumberTextField.setMinimumSize(new Dimension(100, 30));
        phoneNumberTextField.setPreferredSize(new Dimension(100, 30));
        phoneNumberTextField.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        signUpPanel.add(phoneNumberTextField, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        signUpPanel.add(spacer3, gbc);
        userNameLabel = new JLabel();
        userNameLabel.setText("User Name");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        signUpPanel.add(userNameLabel, gbc);
        userNameTextField = new JTextField();
        userNameTextField.setMinimumSize(new Dimension(100, 30));
        userNameTextField.setPreferredSize(new Dimension(100, 30));
        userNameTextField.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        signUpPanel.add(userNameTextField, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        signUpPanel.add(spacer4, gbc);
        passwordLabel = new JLabel();
        passwordLabel.setText("Password");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        signUpPanel.add(passwordLabel, gbc);
        passwordPasswordField = new JPasswordField();
        passwordPasswordField.setMinimumSize(new Dimension(100, 30));
        passwordPasswordField.setPreferredSize(new Dimension(100, 30));
        passwordPasswordField.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        signUpPanel.add(passwordPasswordField, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.VERTICAL;
        signUpPanel.add(spacer5, gbc);
        signUpButton = new JButton();
        signUpButton.setText("Sign Up");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        signUpPanel.add(signUpButton, gbc);
        nameLabel.setLabelFor(nameTextField);
        phoneNumberLabel.setLabelFor(phoneNumberTextField);
        userNameLabel.setLabelFor(userNameTextField);
        passwordLabel.setLabelFor(passwordPasswordField);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return signUpPanel;
    }
}
