package com.bank.atm.gui.loans;

import javax.swing.*;
import java.awt.*;

public class RequestLoansUI extends JFrame {
    private final int frameWidth = 500;
    private final int frameHeight = 500;
    private JFormattedTextField loanAmountRequested;
    private JFormattedTextField formattedTextField1;
    private JButton requestLoanButton;
    private JPanel requestLoansPanel;

    public RequestLoansUI() {

        $$$setupUI$$$();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setContentPane(requestLoansPanel);//sets content to our menu panel
        this.setPreferredSize(new Dimension(frameWidth, frameHeight));//set width and height of our frame
        this.pack(); //packs frame to preferred size
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        requestLoansPanel = new JPanel();
        requestLoansPanel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Amount Requested:");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        requestLoansPanel.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        requestLoansPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        requestLoansPanel.add(spacer2, gbc);
        loanAmountRequested = new JFormattedTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        requestLoansPanel.add(loanAmountRequested, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Collateral:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        requestLoansPanel.add(label2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        requestLoansPanel.add(spacer3, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Interest");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        requestLoansPanel.add(label3, gbc);
        formattedTextField1 = new JFormattedTextField();
        formattedTextField1.setEditable(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        requestLoansPanel.add(formattedTextField1, gbc);
        requestLoanButton = new JButton();
        requestLoanButton.setText("Request Loan");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        requestLoansPanel.add(requestLoanButton, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.VERTICAL;
        requestLoansPanel.add(spacer4, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Request Loan");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        requestLoansPanel.add(label4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        requestLoansPanel.add(spacer5, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return requestLoansPanel;
    }
}
