package com.bank.atm.gui.banker;

import com.bank.atm.backend.collections.UsersCollectionManager;
import com.bank.atm.backend.users.User;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;

public class BankerMenu extends JFrame {
    private JPanel bankerMenuPanel;
    private JButton viewUsersButton;
    private JButton viewLoansButton;
    private JButton dailyTransactionReportsButton;
    private JTextField searchUserTextField;
    private JButton searchUserButton;
    private JPanel buttonPanel;
    private JPanel searchPanel;

    public BankerMenu(String title) {
        super(title);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setContentPane(bankerMenuPanel);
        this.setPreferredSize(new Dimension(500, 300));//set width and height of our frame
        this.pack();
        this.setLocationRelativeTo(null);

        viewUsersButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                JFrame frame = new ViewUser("View Users",new ArrayList<>());
                frame.setVisible(true);
            }
        });

        viewLoansButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });

        dailyTransactionReportsButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                JFrame frame = new DailyTransactionReports("Daily Transaction Report");
                frame.setVisible(true);
            }
        });
        searchUserButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String searchString = searchUserTextField.getText().trim();
                UsersCollectionManager usersCollectionManager = UsersCollectionManager.getInstance();
                List<User> searchedUsers = new ArrayList<User>();
                searchedUsers.addAll(usersCollectionManager.findByFirstName(searchString));
                searchedUsers.addAll(usersCollectionManager.findByLastName(searchString));
                dispose();
                JFrame frame = new ViewUser("View Users",searchedUsers);
                frame.setVisible(true);
            }
        });
    }

    public static void main(String[] args) {
        JFrame frame = new BankerMenu("Banker Menu");
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        bankerMenuPanel = new JPanel();
        bankerMenuPanel.setLayout(new GridBagLayout());
        viewUsersButton = new JButton();
        viewUsersButton.setText("View Users");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        bankerMenuPanel.add(viewUsersButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        bankerMenuPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        bankerMenuPanel.add(spacer2, gbc);
        viewLoansButton = new JButton();
        viewLoansButton.setText("View Loans");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        bankerMenuPanel.add(viewLoansButton, gbc);
        dailyTransactionReportsButton = new JButton();
        dailyTransactionReportsButton.setText("Daily Transaction Reports");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        bankerMenuPanel.add(dailyTransactionReportsButton, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        bankerMenuPanel.add(spacer3, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return bankerMenuPanel;
    }
}
