package com.bank.atm.gui.banker;

import com.bank.atm.backend.collections.UsersCollectionManager;
import com.bank.atm.backend.users.User;
import com.bank.atm.util.ID;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Navoneel Ghosh
 * GUI for the banker. Enables the banker to get the list of all clients and get further details of a particular client
 * by double clicking the row in the table.
 */
public class ViewUser extends JFrame {
    private JPanel viewUserPanel;
    private JScrollPane viewUserScrollPane;
    private JTable viewUserTable;
    private JButton backButton;
    private JPanel backPanel;
    private JPanel searchUserPanel;
    private JTextField searchUserTextField;
    private JButton searchUserButton;
    private List<User> clientList;

    public ViewUser(String title, List<User> searchedUsers) {
        super(title);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setContentPane(viewUserPanel);
        this.setPreferredSize(new Dimension(800, 500));//set width and height of our frame
        this.pack();
        this.setLocationRelativeTo(null);
        this.createViewUserTable(searchedUsers);
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                JFrame frame = new BankerMenu("Banker Menu");
                frame.setVisible(true);
            }
        });
        searchUserButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String searchString = searchUserTextField.getText().trim();
                UsersCollectionManager usersCollectionManager = UsersCollectionManager.getInstance();
                List<User> searchedUsersList = new ArrayList<User>();
                searchedUsersList.addAll(usersCollectionManager.findByFirstName(searchString));
                searchedUsersList.addAll(usersCollectionManager.findByLastName(searchString));
                createViewUserTable(searchedUsersList);
            }
        });
    }

    private void createViewUserTable(List<User> searchedUsers) {
        String[] columnNames = {"User ID", "First Name",
                "Last Name"};

        this.clientList = new ArrayList<User>();
        try {
            if (searchedUsers == null || searchedUsers.isEmpty()) {
                this.clientList.addAll(UsersCollectionManager.getInstance().allClients());
            } else {
                this.clientList.addAll(searchedUsers);
            }
        } catch (Exception e) {

        }

        ViewUserCustomTableModel viewUserCustomTableModel = new ViewUserCustomTableModel(this.clientList, columnNames);
        viewUserTable.setModel(viewUserCustomTableModel);
        viewUserTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2 && viewUserTable.getSelectedRow() != -1) {
                    ID selectedUserID = viewUserCustomTableModel.getIdAt(viewUserTable.getSelectedRow());
                    dispose();
                    JFrame frame = new ViewSingleUserDetails("User Details", selectedUserID);
                    frame.setVisible(true);
                }
            }
        });
        viewUserScrollPane.getViewport().add(viewUserTable);
        viewUserTable.setFillsViewportHeight(true);
        viewUserScrollPane.setVisible(true);
        viewUserTable.setVisible(true);
        viewUserTable.setRowHeight(30);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        viewUserPanel = new JPanel();
        viewUserPanel.setLayout(new GridBagLayout());
        viewUserScrollPane = new JScrollPane();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        viewUserPanel.add(viewUserScrollPane, gbc);
        viewUserTable = new JTable();
        viewUserTable.setAutoCreateRowSorter(true);
        viewUserScrollPane.setViewportView(viewUserTable);
        backPanel = new JPanel();
        backPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        viewUserPanel.add(backPanel, gbc);
        backButton = new JButton();
        backButton.setText("Back");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        backPanel.add(backButton, gbc);
        searchUserPanel = new JPanel();
        searchUserPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        viewUserPanel.add(searchUserPanel, gbc);
        searchUserTextField = new JTextField();
        searchUserTextField.setMinimumSize(new Dimension(100, 30));
        searchUserTextField.setPreferredSize(new Dimension(200, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        searchUserPanel.add(searchUserTextField, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        searchUserPanel.add(spacer1, gbc);
        searchUserButton = new JButton();
        searchUserButton.setText("Search User");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        searchUserPanel.add(searchUserButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return viewUserPanel;
    }

}
