package com.bank.atm.gui.banker;

import com.bank.atm.backend.collections.UsersCollectionManager;
import com.bank.atm.backend.users.User;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;

public class ViewUser extends JFrame {
    private JPanel viewUserPanel;
    private JScrollPane viewUserScrollPane;
    private JTable viewUserTable;
    private JButton backButton;
    private JPanel backPanel;

    public ViewUser(String title) {
        super(title);
        $$$setupUI$$$();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setContentPane(viewUserPanel);
        this.setPreferredSize(new Dimension(800, 500));//set width and height of our frame
        this.pack();
        this.setLocationRelativeTo(null);
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                JFrame frame = new BankerMenu("Banker Menu");
                frame.setVisible(true);
            }
        });
    }

    public static void main(String[] args) {
        JFrame frame = new ViewUser("View Users");
        frame.setVisible(true);
    }

    private void createViewUserTable() {
        String[] columnNames = {"First Name",
                "Last Name"};

        List<User> clientList = new ArrayList<User>();
        clientList.addAll(UsersCollectionManager.getInstance().allClients());

        for (User tempClient : clientList) {
            System.out.println(tempClient.getID());
        }

        ViewUserCustomTableModel viewUserCustomTableModel = new ViewUserCustomTableModel(clientList, columnNames);
        viewUserTable = new JTable(viewUserCustomTableModel);
        viewUserTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2 && viewUserTable.getSelectedRow() != -1) {
                    System.out.println("Double Click done");
                    System.out.println(viewUserCustomTableModel.getIdAt(viewUserTable.getSelectedRow()));
                    dispose();
                    JFrame frame = new ViewSingleUserDetails("User Details");
                    frame.setVisible(true);
                }
            }
        });
        viewUserScrollPane = new JScrollPane(viewUserTable);
        viewUserTable.setFillsViewportHeight(true);
        viewUserScrollPane.setVisible(true);
        viewUserTable.setVisible(true);
    }

    private void createUIComponents() {
        this.createViewUserTable();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        viewUserPanel = new JPanel();
        viewUserPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        viewUserPanel.add(viewUserScrollPane, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        viewUserTable.setAutoCreateRowSorter(true);
        viewUserScrollPane.setViewportView(viewUserTable);
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        viewUserPanel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        backPanel = new JPanel();
        backPanel.setLayout(new GridBagLayout());
        viewUserPanel.add(backPanel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        backButton = new JButton();
        backButton.setText("Back");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        backPanel.add(backButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return viewUserPanel;
    }
}
